# API Contract: Todo Chatbot Backend API

openapi: 3.0.0
info:
  title: Todo Chatbot Backend API
  version: 1.0.0
  description: API for the Todo Chatbot backend service

paths:
  /api/todos/:
    get:
      summary: Get all todos for authenticated user
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'

  /api/todos/{id}:
    get:
      summary: Get a specific todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Todo details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    put:
      summary: Update a specific todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    delete:
      summary: Delete a specific todo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Todo deleted successfully
        '404':
          description: Todo not found

  /api/todos/{id}/status:
    patch:
      summary: Update todo completion status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Todo status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found

  /api/{user_id}/chat:
    post:
      summary: Send a message and get AI-powered response
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
      responses:
        '200':
          description: AI-generated response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'

  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: Health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    example: "2026-02-12T10:00:00Z"

  /ready:
    get:
      summary: Readiness check endpoint
      responses:
        '200':
          description: Readiness status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ready"
                  timestamp:
                    type: string
                    example: "2026-02-12T10:00:00Z"

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - title
        - completed
        - created_at
        - updated_at

    CreateTodoRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
      required:
        - title

    UpdateTodoRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean

    UpdateStatusRequest:
      type: object
      properties:
        completed:
          type: boolean
      required:
        - completed

    ChatMessageRequest:
      type: object
      properties:
        message:
          type: string
          description: The user's message to the AI
        conversation_id:
          type: string
          format: uuid
          description: Optional conversation ID to continue a conversation
      required:
        - message

    ChatMessageResponse:
      type: object
      properties:
        conversation_id:
          type: string
          format: uuid
          description: The conversation ID
        message:
          type: string
          description: The AI-generated response
      required:
        - conversation_id
        - message