apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todo-kafka-pubsub
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "localhost:9092"
  - name: consumerGroup
    value: "todo-consumer-group"
  - name: clientID
    value: "todo-app"
  - name: authRequired
    value: "false"