#!/bin/bash
# Health monitoring script for deployed Todo Chatbot components
# Generated by kubectl-ai based on Phase 4 spec

set -e  # Exit on any error

echo "Starting health monitoring for Todo Chatbot components..."

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "Error: kubectl is not installed"
    exit 1
fi

# Check if Helm is available
if ! command -v helm &> /dev/null; then
    echo "Error: Helm is not installed"
    exit 1
fi

# Set the release name
RELEASE_NAME="todo-chatbot"

# Check if the Helm release exists
if ! helm status $RELEASE_NAME &> /dev/null; then
    echo "Error: Helm release $RELEASE_NAME is not deployed"
    exit 1
fi

echo "Helm release $RELEASE_NAME exists"

# Function to check component health
check_component_health() {
    local component=$1
    local label_selector=$2
    
    echo "Checking health of $component..."
    
    # Get pods for the component
    PODS=$(kubectl get pods -l $label_selector -o jsonpath='{.items[*].metadata.name}' 2>/dev/null)
    
    if [ -z "$PODS" ]; then
        echo "❌ No $component pods found"
        return 1
    fi
    
    echo "Found pods: $PODS"
    
    # Check each pod's status
    local all_healthy=true
    for pod in $PODS; do
        # Get pod status
        POD_STATUS=$(kubectl get pod $pod -o jsonpath='{.status.phase}')
        READY_STATUS=$(kubectl get pod $pod -o jsonpath='{range .status.containerStatuses[*]}{.ready}{" "}{end}')
        
        echo "  Pod: $pod, Status: $POD_STATUS, Ready: $READY_STATUS"
        
        # Check if pod is running and ready
        if [ "$POD_STATUS" != "Running" ]; then
            echo "    ❌ Pod $pod is not running (status: $POD_STATUS)"
            all_healthy=false
        fi
        
        # Check if all containers in the pod are ready
        for status in $READY_STATUS; do
            if [ "$status" != "true" ]; then
                echo "    ❌ Pod $pod has unready containers"
                all_healthy=false
            fi
        done
        
        # Check restart count
        RESTART_COUNT=$(kubectl get pod $pod -o jsonpath='{.status.containerStatuses[0].restartCount}')
        if [ "$RESTART_COUNT" -gt 5 ]; then
            echo "    ⚠️  Pod $pod has restarted $RESTART_COUNT times"
        else
            echo "    ✅ Pod $pod restart count is normal ($RESTART_COUNT)"
        fi
    done
    
    # Check deployment status
    DEPLOYMENT=$(kubectl get deployments -l $label_selector -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
    if [ -n "$DEPLOYMENT" ]; then
        DESIRED_REPLICAS=$(kubectl get deployment $DEPLOYMENT -o jsonpath='{.spec.replicas}')
        CURRENT_REPLICAS=$(kubectl get deployment $DEPLOYMENT -o jsonpath='{.status.replicas}')
        READY_REPLICAS=$(kubectl get deployment $DEPLOYMENT -o jsonpath='{.status.readyReplicas}')
        UPDATED_REPLICAS=$(kubectl get deployment $DEPLOYMENT -o jsonpath='{.status.updatedReplicas}')
        AVAILABLE_REPLICAS=$(kubectl get deployment $DEPLOYMENT -o jsonpath='{.status.availableReplicas}')
        
        echo "  Deployment: $DEPLOYMENT"
        echo "    Desired: $DESIRED_REPLICAS, Current: $CURRENT_REPLICAS, Ready: $READY_REPLICAS"
        echo "    Updated: $UPDATED_REPLICAS, Available: $AVAILABLE_REPLICAS"
        
        if [ "$READY_REPLICAS" -lt "$DESIRED_REPLICAS" ]; then
            echo "    ❌ Deployment $DEPLOYMENT has insufficient ready replicas ($READY_REPLICAS/$DESIRED_REPLICAS)"
            all_healthy=false
        else
            echo "    ✅ Deployment $DEPLOYMENT has sufficient ready replicas ($READY_REPLICAS/$DESIRED_REPLICAS)"
        fi
    else
        echo "  ⚠️  No deployment found for $label_selector"
    fi
    
    if [ "$all_healthy" = true ]; then
        echo "✅ $component is healthy"
        return 0
    else
        echo "❌ $component has health issues"
        return 1
    fi
}

# Check backend health
check_component_health "backend" "app=backend"

# Check frontend health
check_component_health "frontend" "app=frontend"

# Check service connectivity
echo "Checking service connectivity..."
SERVICES=$(kubectl get services -o jsonpath='{.items[*].metadata.name}')

for service in $SERVICES; do
    if [[ $service == *"backend"* ]]; then
        echo "Checking backend service: $service"
        SERVICE_TYPE=$(kubectl get service $service -o jsonpath='{.spec.type}')
        SERVICE_PORT=$(kubectl get service $service -o jsonpath='{.spec.ports[0].port}')
        SERVICE_CLUSTER_IP=$(kubectl get service $service -o jsonpath='{.spec.clusterIP}')
        
        echo "  Type: $SERVICE_TYPE, Port: $SERVICE_PORT, ClusterIP: $SERVICE_CLUSTER_IP"
        
        # Check endpoints
        ENDPOINTS=$(kubectl get endpoints $service -o jsonpath='{range .subsets[0].addresses[*]}{.ip}{" "}{end}' 2>/dev/null)
        if [ -n "$ENDPOINTS" ]; then
            echo "  Endpoints: $ENDPOINTS"
        else
            echo "  ⚠️  No active endpoints for service $service"
        fi
    elif [[ $service == *"frontend"* ]]; then
        echo "Checking frontend service: $service"
        SERVICE_TYPE=$(kubectl get service $service -o jsonpath='{.spec.type}')
        SERVICE_PORT=$(kubectl get service $service -o jsonpath='{.spec.ports[0].port}')
        SERVICE_NODEPORT=$(kubectl get service $service -o jsonpath='{.spec.ports[0].nodePort}' 2>/dev/null)
        
        echo "  Type: $SERVICE_TYPE, Port: $SERVICE_PORT, NodePort: $SERVICE_NODEPORT"
        
        # Check endpoints
        ENDPOINTS=$(kubectl get endpoints $service -o jsonpath='{range .subsets[0].addresses[*]}{.ip}{" "}{end}' 2>/dev/null)
        if [ -n "$ENDPOINTS" ]; then
            echo "  Endpoints: $ENDPOINTS"
        else
            echo "  ⚠️  No active endpoints for service $service"
        fi
    fi
done

# Check resource usage
echo "Checking resource usage..."
if command -v kubectl-top &> /dev/null || kubectl top nodes &> /dev/null; then
    echo "Resource usage for backend pods:"
    kubectl top pods -l app=backend 2>/dev/null || echo "  Metrics not available for backend"
    
    echo "Resource usage for frontend pods:"
    kubectl top pods -l app=frontend 2>/dev/null || echo "  Metrics not available for frontend"
else
    echo "Metrics server not available, skipping resource usage check"
fi

# Check for events that might indicate problems
echo "Checking for warning events..."
WARNING_EVENTS=$(kubectl get events --field-selector type=Warning --all-namespaces --sort-by='.lastTimestamp' 2>/dev/null | grep -i -E "(todo-chatbot|backend|frontend)" | tail -5)

if [ -n "$WARNING_EVENTS" ]; then
    echo "⚠️  WARNING EVENTS FOUND:"
    echo "$WARNING_EVENTS"
else
    echo "✅ No recent warning events found"
fi

# Perform health check requests if possible
echo "Performing health check requests..."

# Check backend health endpoint if accessible
BACKEND_SERVICE=$(kubectl get svc -l app=backend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
if [ -n "$BACKEND_SERVICE" ]; then
    # Try to access the health endpoint internally using kubectl port-forward or exec
    BACKEND_POD=$(kubectl get pods -l app=backend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
    if [ -n "$BACKEND_POD" ]; then
        echo "Checking backend health via pod exec..."
        HEALTH_STATUS=$(kubectl exec $BACKEND_POD -- curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health 2>/dev/null || echo "000")
        if [ "$HEALTH_STATUS" = "200" ]; then
            echo "✅ Backend health endpoint is responding (HTTP $HEALTH_STATUS)"
        else
            echo "⚠️  Backend health endpoint response: HTTP $HEALTH_STATUS"
        fi
        
        READY_STATUS=$(kubectl exec $BACKEND_POD -- curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/ready 2>/dev/null || echo "000")
        if [ "$READY_STATUS" = "200" ]; then
            echo "✅ Backend ready endpoint is responding (HTTP $READY_STATUS)"
        else
            echo "⚠️  Backend ready endpoint response: HTTP $READY_STATUS"
        fi
    else
        echo "⚠️  Could not check backend health - no backend pod found"
    fi
else
    echo "⚠️  Could not check backend health - no backend service found"
fi

# Check frontend health
FRONTEND_SERVICE=$(kubectl get svc -l app=frontend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
if [ -n "$FRONTEND_SERVICE" ]; then
    FRONTEND_POD=$(kubectl get pods -l app=frontend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)
    if [ -n "$FRONTEND_POD" ]; then
        echo "Checking frontend health via pod exec..."
        ROOT_STATUS=$(kubectl exec $FRONTEND_POD -- curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/ 2>/dev/null || echo "000")
        if [ "$ROOT_STATUS" = "200" ] || [ "$ROOT_STATUS" = "404" ]; then  # 404 is OK for SPA
            echo "✅ Frontend root endpoint is responding (HTTP $ROOT_STATUS)"
        else
            echo "⚠️  Frontend root endpoint response: HTTP $ROOT_STATUS"
        fi
    else
        echo "⚠️  Could not check frontend health - no frontend pod found"
    fi
else
    echo "⚠️  Could not check frontend health - no frontend service found"
fi

echo ""
echo "🎉 Health monitoring completed!"
echo ""
echo "Summary:"
echo "- Backend health: $(if check_component_health "backend" "app=backend" >/dev/null 2>&1; then echo "OK"; else echo "ISSUES"; fi)"
echo "- Frontend health: $(if check_component_health "frontend" "app=frontend" >/dev/null 2>&1; then echo "OK"; else echo "ISSUES"; fi)"
echo "- Services: Checked"
echo "- Resource usage: Monitored (if metrics available)"
echo "- Events: Checked for warnings"
echo ""
echo "For continuous monitoring, consider setting up Prometheus and Grafana."