#!/bin/bash
# Scaling execution script for Todo Chatbot frontend
# Generated by Qwen based on Phase 4 spec

set -e  # Exit on any error

echo "Scaling frontend deployment to minimum 2 replicas..."

# Check if kubectl is available
if ! command -v kubectl &> /dev/null; then
    echo "Error: kubectl is not installed"
    exit 1
fi

# Check if Helm is available
if ! command -v helm &> /dev/null; then
    echo "Error: Helm is not installed"
    exit 1
fi

# Set the release name
RELEASE_NAME="todo-chatbot"

# Check if the Helm release exists
if ! helm status $RELEASE_NAME &> /dev/null; then
    echo "Error: Helm release $RELEASE_NAME is not deployed"
    exit 1
fi

# Get the frontend deployment name
FRONTEND_DEPLOYMENT=$(kubectl get deployments -l app=frontend -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)

if [ -z "$FRONTEND_DEPLOYMENT" ]; then
    echo "Error: Frontend deployment not found"
    exit 1
fi

echo "Found frontend deployment: $FRONTEND_DEPLOYMENT"

# Get current replica count
CURRENT_REPLICAS=$(kubectl get deployment $FRONTEND_DEPLOYMENT -o jsonpath='{.spec.replicas}')
echo "Current replica count: $CURRENT_REPLICAS"

# Check if scaling is needed
if [ "$CURRENT_REPLICAS" -lt 2 ]; then
    echo "Scaling frontend deployment from $CURRENT_REPLICAS to 2 replicas..."
    kubectl scale deployment $FRONTEND_DEPLOYMENT --replicas=2
    
    # Wait for deployment to be ready
    echo "Waiting for deployment to be ready..."
    kubectl rollout status deployment/$FRONTEND_DEPLOYMENT --timeout=180s
    
    # Verify the new replica count
    ACTUAL_REPLICAS=$(kubectl get deployment $FRONTEND_DEPLOYMENT -o jsonpath='{.status.readyReplicas}')
    echo "Deployment now has $ACTUAL_REPLICAS ready replicas"
    
    if [ "$ACTUAL_REPLICAS" -ge 2 ]; then
        echo "✅ Frontend successfully scaled to 2+ replicas"
    else
        echo "❌ Failed to scale frontend to 2 replicas. Only $ACTUAL_REPLICAS are ready."
        exit 1
    fi
else
    echo "Frontend already has $CURRENT_REPLICAS replicas (≥2), no scaling needed"
    
    # Verify that the current replicas are ready
    READY_REPLICAS=$(kubectl get deployment $FRONTEND_DEPLOYMENT -o jsonpath='{.status.readyReplicas}')
    if [ "$READY_REPLICAS" -lt 2 ]; then
        echo "⚠️  Warning: Frontend has $CURRENT_REPLICAS requested replicas but only $READY_REPLICAS are ready"
        echo "Retrying rollout status..."
        kubectl rollout status deployment/$FRONTEND_DEPLOYMENT --timeout=180s
    else
        echo "✅ Frontend has $READY_REPLICAS ready replicas (≥2)"
    fi
fi

# Check if Horizontal Pod Autoscaler is configured
HPA_EXISTS=$(kubectl get hpa -l app=frontend 2>/dev/null | grep -c "todo-chatbot-frontend" || echo "0")

if [ "$HPA_EXISTS" -gt 0 ]; then
    echo "Horizontal Pod Autoscaler is configured for frontend"
    kubectl get hpa -l app=frontend
else
    echo "No Horizontal Pod Autoscaler configured for frontend (this is OK for basic scaling)"
fi

# Show final status
echo ""
echo "Final deployment status:"
kubectl get deployment $FRONTEND_DEPLOYMENT
kubectl get pods -l app=frontend

# Run validation to confirm scaling
echo ""
echo "Running validation to confirm scaling..."
bash scripts/validate-scaling.sh

echo ""
echo "🎉 Frontend scaling operation completed!"
echo "Deployment: $FRONTEND_DEPLOYMENT"
echo "Replicas: $CURRENT_REPLICAS → $(kubectl get deployment $FRONTEND_DEPLOYMENT -o jsonpath='{.spec.replicas}') (desired)"
echo "Ready: $(kubectl get deployment $FRONTEND_DEPLOYMENT -o jsonpath='{.status.readyReplicas}') (ready)"