#!/bin/bash
# Minikube setup script for Todo Chatbot
# Generated by Qwen based on Phase 4 spec

set -e  # Exit on any error

echo "Setting up Minikube for Todo Chatbot deployment..."

# Check if Minikube is installed
if ! command -v minikube &> /dev/null; then
    echo "Minikube is not installed. Please install it first."
    echo "For Windows: choco install minikube"
    echo "For macOS: brew install minikube"
    echo "For Linux: Follow instructions at https://minikube.sigs.k8s.io/docs/start/"
    exit 1
fi

# Check if kubectl is installed
if ! command -v kubectl &> /dev/null; then
    echo "kubectl is not installed. Please install it first."
    echo "Follow instructions at https://kubernetes.io/docs/tasks/tools/"
    exit 1
fi

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "Docker is not installed. Please install Docker Desktop or Docker Engine first."
    exit 1
fi

# Check if Helm is installed
if ! command -v helm &> /dev/null; then
    echo "Helm is not installed. Installing Helm..."
    # Install Helm based on OS
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        brew install helm
    elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
        choco install kubernetes-helm
    else
        echo "Unsupported OS. Please install Helm manually."
        exit 1
    fi
fi

# Start Minikube with recommended settings for Todo Chatbot
MINIKUBE_PROFILE="todo-chatbot"
echo "Starting Minikube with profile: $MINIKUBE_PROFILE"

# Check if cluster is already running
if minikube status -p $MINIKUBE_PROFILE &> /dev/null; then
    echo "Minikube cluster '$MINIKUBE_PROFILE' is already running."
else
    # Start Minikube with appropriate resources for Todo Chatbot
    minikube start \
        --profile=$MINIKUBE_PROFILE \
        --driver=docker \
        --cpus=4 \
        --memory=8192mb \
        --disk-size=40gb \
        --kubernetes-version=latest
    
    echo "Minikube cluster '$MINIKUBE_PROFILE' started successfully."
fi

# Enable required Minikube addons
echo "Enabling required Minikube addons..."
minikube addons enable ingress --profile=$MINIKUBE_PROFILE
minikube addons enable metrics-server --profile=$MINIKUBE_PROFILE

# Verify cluster status
echo "Verifying cluster status..."
kubectl cluster-info --context=minikube-$MINIKUBE_PROFILE

# Verify nodes
echo "Verifying nodes..."
kubectl get nodes

echo "Minikube setup for Todo Chatbot completed successfully!"
echo ""
echo "Next steps:"
echo "1. Build Docker images for backend and frontend"
echo "2. Load images into Minikube: minikube image load <image-name>"
echo "3. Deploy using Helm: helm install todo-chatbot charts/todo-chatbot/"