#!/bin/bash
# Project structure validation script for Todo Chatbot
# Generated by Qwen based on Phase 4 spec

set -e  # Exit on any error

echo "Validating Todo Chatbot project structure..."

# Define expected directories
EXPECTED_DIRS=(
    "backend"
    "frontend" 
    "charts"
    "charts/todo-chatbot"
    "charts/todo-chatbot/templates"
    "scripts"
    "docs"
)

# Define expected files
EXPECTED_FILES=(
    "backend/Dockerfile"
    "frontend/Dockerfile"
    "charts/todo-chatbot/Chart.yaml"
    "charts/todo-chatbot/values.yaml"
    "specs/001-k8s-deployment/spec.md"
    "specs/001-k8s-deployment/plan.md"
    "specs/001-k8s-deployment/tasks.md"
)

# Validate directories
echo "Checking required directories..."
MISSING_DIRS=()
for dir in "${EXPECTED_DIRS[@]}"; do
    if [ ! -d "$dir" ]; then
        MISSING_DIRS+=("$dir")
        echo "❌ Missing directory: $dir"
    else
        echo "✅ Found directory: $dir"
    fi
done

# Validate files
echo "Checking required files..."
MISSING_FILES=()
for file in "${EXPECTED_FILES[@]}"; do
    if [ ! -f "$file" ]; then
        MISSING_FILES+=("$file")
        echo "❌ Missing file: $file"
    else
        echo "✅ Found file: $file"
    fi
done

# Check for Helm chart structure
echo "Checking Helm chart structure..."
HELM_CHART_PATH="charts/todo-chatbot"
if [ -d "$HELM_CHART_PATH" ]; then
    HELM_TEMPLATES="$HELM_CHART_PATH/templates"
    if [ -d "$HELM_TEMPLATES" ]; then
        echo "✅ Helm templates directory exists"
        
        # Check for required templates
        REQUIRED_TEMPLATES=("backend-deployment.yaml" "frontend-deployment.yaml" "backend-service.yaml" "frontend-service.yaml")
        for template in "${REQUIRED_TEMPLATES[@]}"; do
            if [ -f "$HELM_TEMPLATES/$template" ]; then
                echo "✅ Found Helm template: $template"
            else
                echo "❌ Missing Helm template: $template"
                MISSING_FILES+=("$HELM_TEMPLATES/$template")
            fi
        done
    else
        echo "❌ Helm templates directory missing: $HELM_TEMPLATES"
        MISSING_DIRS+=("$HELM_TEMPLATES")
    fi
    
    # Check for required Helm files
    if [ -f "$HELM_CHART_PATH/Chart.yaml" ]; then
        echo "✅ Found Chart.yaml"
    else
        echo "❌ Missing Chart.yaml"
        MISSING_FILES+=("$HELM_CHART_PATH/Chart.yaml")
    fi
    
    if [ -f "$HELM_CHART_PATH/values.yaml" ]; then
        echo "✅ Found values.yaml"
    else
        echo "❌ Missing values.yaml"
        MISSING_FILES+=("$HELM_CHART_PATH/values.yaml")
    fi
else
    echo "❌ Helm chart directory missing: $HELM_CHART_PATH"
    MISSING_DIRS+=("$HELM_CHART_PATH")
fi

# Check for Dockerfiles
echo "Checking Dockerfiles..."
if [ -f "backend/Dockerfile" ]; then
    echo "✅ Found backend Dockerfile"
else
    echo "❌ Missing backend Dockerfile"
    MISSING_FILES+=("backend/Dockerfile")
fi

if [ -f "frontend/Dockerfile" ]; then
    echo "✅ Found frontend Dockerfile"
else
    echo "❌ Missing frontend Dockerfile"
    MISSING_FILES+=("frontend/Dockerfile")
fi

# Check for application source directories
echo "Checking application source directories..."
if [ -d "backend/src" ]; then
    echo "✅ Found backend source directory"
else
    echo "⚠️  Backend source directory missing (might be intentional)"
fi

if [ -d "frontend/src" ]; then
    echo "✅ Found frontend source directory"
else
    echo "⚠️  Frontend source directory missing (might be intentional)"
fi

# Summary
TOTAL_MISSING=$((${#MISSING_DIRS[@]} + ${#MISSING_FILES[@]}))

if [ $TOTAL_MISSING -eq 0 ]; then
    echo ""
    echo "🎉 Project structure validation PASSED!"
    echo "All required directories and files are present."
    exit 0
else
    echo ""
    echo "💥 Project structure validation FAILED!"
    echo "Missing ${#MISSING_DIRS[@]} directories and ${#MISSING_FILES[@]} files."
    
    if [ ${#MISSING_DIRS[@]} -gt 0 ]; then
        echo ""
        echo "Missing directories:"
        for dir in "${MISSING_DIRS[@]}"; do
            echo "  - $dir"
        done
    fi
    
    if [ ${#MISSING_FILES[@]} -gt 0 ]; then
        echo ""
        echo "Missing files:"
        for file in "${MISSING_FILES[@]}"; do
            echo "  - $file"
        done
    fi
    
    echo ""
    echo "Please create the missing directories and files before proceeding."
    exit 1
fi